/**
 * Central game registry for the main_web game library.
 *
 * To add a NEW game to the library, just add one object to this array.
 * No HTML / JS changes required - the front-end renders everything
 * dynamically from this single source of truth.
 */

const games = [
  {
    id: 'maze-runner',
    title: 'Maze Runner',
    description:
      'Navigate the winding labyrinth, dodge dead-ends and race to the finish as fast as you can.',
    url: '/games/maze-runner/',
    emoji: '🕹️',
    gradient: 'linear-gradient(135deg, #0ea5e9, #6366f1)',
    tags: ['puzzle', 'adventure'],
    difficulty: 2,
    featured: true,
    status: 'live',
  },
  {
    id: 'tic-tac-toe',
    title: 'Tic-Tac-Toe',
    description:
      'The classic battle of X and O. Play head-to-head or challenge the unbeatable AI.',
    url: '/games/tic-tac-toe/',
    emoji: '⭕',
    gradient: 'linear-gradient(135deg, #22c55e, #10b981)',
    tags: ['strategy', 'classic'],
    difficulty: 1,
    featured: false,
    status: 'live',
  },
  {
    id: 'snake-arena',
    title: 'Snake Arena',
    description:
      'Eat, grow, and survive. Speed ramps up as your snake slithers toward a high score.',
    url: '/games/snake-arena/',
    emoji: '🐍',
    gradient: 'linear-gradient(135deg, #f59e0b, #ef4444)',
    tags: ['arcade', 'highscore'],
    difficulty: 3,
    featured: false,
    status: 'live',
  },
  {
    id: 'memory-match',
    title: 'Memory Match',
    description:
      'Flip the cards, test your recall and pair every tile before the timer runs out.',
    url: '/games/memory-match/',
    emoji: '🧠',
    gradient: 'linear-gradient(135deg, #ec4899, #8b5cf6)',
    tags: ['puzzle', 'classic'],
    difficulty: 1,
    featured: false,
    status: 'live',
  },
  {
    id: 'sudoku',
    title: 'Sudoku',
    description:
      'A brain workout of logic and numbers. Fill the grid with every row, column and box resolved.',
    url: '/games/sudoku/',
    emoji: '🔢',
    gradient: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
    tags: ['puzzle', 'strategy'],
    difficulty: 4,
    featured: false,
    status: 'live',
  },
  {
    id: 'breakout',
    title: 'Breakout Blast',
    description:
      'Bounce the ball, smash every brick and clear the board before you run out of lives.',
    url: '/games/breakout/',
    emoji: '🏓',
    gradient: 'linear-gradient(135deg, #f43f5e, #f97316)',
    tags: ['arcade', 'action'],
    difficulty: 3,
    featured: false,
    status: 'live',
  },
  {
    id: 'gravity-switch',
    title: 'Gravity Switch',
    description:
      'Flip gravity, slip between walls, collect every crystal and escape the shifting vault alive.',
    url: '/games/gravity-switch/',
    emoji: '🪐',
    gradient: 'linear-gradient(135deg, #14b8a6, #0f766e)',
    tags: ['puzzle', 'arcade'],
    difficulty: 3,
    featured: false,
    status: 'live',
  },
  {
    id: 'neon-circuit',
    title: 'Neon Circuit',
    description:
      'Rotate the live network, route power through every junction and light the reactor before the grid overloads.',
    url: '/games/neon-circuit/',
    emoji: '⚡',
    gradient: 'linear-gradient(135deg, #f43f5e, #8b5cf6)',
    tags: ['puzzle', 'strategy'],
    difficulty: 4,
    featured: false,
    status: 'live',
  },
  {
    id: 'tetris',
    title: 'Tetris',
    description: 'Stack falling blocks, clear lines and chase a higher score with every level.',
    url: '/games/tetris/',
    emoji: '🧱',
    gradient: 'linear-gradient(135deg, #7c3aed, #ec4899)',
    tags: ['arcade', 'classic', 'highscore'],
    difficulty: 3,
    featured: false,
    status: 'live',
    publishedAt: '2026-08-20',
    popularity: 88,
  },
  {
    id: 'minesweeper',
    title: 'Minesweeper',
    description: 'Read the clues, mark the mines and clear the board without making one wrong move.',
    url: '/games/minesweeper/',
    emoji: '💣',
    gradient: 'linear-gradient(135deg, #0f766e, #22c55e)',
    tags: ['puzzle', 'strategy', 'classic'],
    difficulty: 3,
    featured: false,
    status: 'live',
    publishedAt: '2026-08-20',
    popularity: 82,
  },
  {
    id: 'rock-paper-scissors',
    title: 'Rock Paper Scissors',
    description: 'Beat the computer in a fast best-of-five duel of timing, luck and mind games.',
    url: '/games/rock-paper-scissors/',
    emoji: '✊',
    gradient: 'linear-gradient(135deg, #f97316, #eab308)',
    tags: ['classic', 'strategy', 'multiplayer'],
    difficulty: 1,
    featured: false,
    status: 'live',
    publishedAt: '2026-08-20',
    popularity: 79,
  },
  {
    id: '2048',
    title: '2048',
    description: 'Slide matching tiles together, build the 2048 tile and chase your personal best.',
    url: '/games/2048/',
    emoji: '🔢',
    gradient: 'linear-gradient(135deg, #f59e0b, #f97316)',
    tags: ['puzzle', 'strategy', 'classic', 'highscore'],
    difficulty: 3,
    featured: false,
    status: 'live',
    publishedAt: '2026-08-20',
    popularity: 86,
  },
  {
    id: 'pong',
    title: 'Pong Duel',
    description: 'Keep the rally alive, outsmart the computer paddle and reach seven points first.',
    url: '/games/pong/',
    emoji: '🏓',
    gradient: 'linear-gradient(135deg, #06b6d4, #2563eb)',
    tags: ['arcade', 'classic', 'action'],
    difficulty: 2,
    featured: false,
    status: 'live',
    publishedAt: '2026-08-20',
    popularity: 77,
  },
  {
    id: 'whack-a-mole',
    title: 'Whack-a-Mole',
    description: 'React fast, hit the targets and score as many points as possible before time runs out.',
    url: '/games/whack-a-mole/',
    emoji: '🔨',
    gradient: 'linear-gradient(135deg, #22c55e, #14b8a6)',
    tags: ['arcade', 'action', 'highscore'],
    difficulty: 2,
    featured: false,
    status: 'live',
    publishedAt: '2026-08-20',
    popularity: 75,
  },
  { id: 'flappy-bird', title: 'Flappy Bird', description: 'Guide the little flyer through the gates and survive as long as possible.', url: '/games/flappy-bird/', emoji: '🐦', gradient: 'linear-gradient(135deg, #38bdf8, #22c55e)', tags: ['arcade', 'action', 'highscore'], difficulty: 3, featured: false, status: 'live', publishedAt: '2026-08-20', popularity: 74 },
  { id: 'connect-four', title: 'Connect Four', description: 'Drop four discs in a row before the computer finds the winning line.', url: '/games/connect-four/', emoji: '🔴', gradient: 'linear-gradient(135deg, #ef4444, #2563eb)', tags: ['strategy', 'classic', 'multiplayer'], difficulty: 2, featured: false, status: 'live', publishedAt: '2026-08-20', popularity: 72 },
  { id: 'hangman', title: 'Hangman', description: 'Guess the hidden word one letter at a time before the drawing is complete.', url: '/games/hangman/', emoji: '🔤', gradient: 'linear-gradient(135deg, #a78bfa, #ec4899)', tags: ['puzzle', 'classic', 'strategy'], difficulty: 2, featured: false, status: 'live', publishedAt: '2026-08-20', popularity: 69 },
  { id: 'typing-speed', title: 'Typing Speed', description: 'Type the prompt accurately and measure your words per minute.', url: '/games/typing-speed/', emoji: '⌨️', gradient: 'linear-gradient(135deg, #14b8a6, #06b6d4)', tags: ['skill', 'highscore', 'classic'], difficulty: 2, featured: false, status: 'live', publishedAt: '2026-08-20', popularity: 68 },
  { id: 'coin-flip', title: 'Coin Flip', description: 'Call heads or tails and see how long your lucky streak can last.', url: '/games/coin-flip/', emoji: '🪙', gradient: 'linear-gradient(135deg, #eab308, #f97316)', tags: ['classic', 'casual'], difficulty: 1, featured: false, status: 'live', publishedAt: '2026-08-20', popularity: 64 },
  { id: 'simon-says', title: 'Simon Says', description: 'Remember the growing color sequence and repeat it without a mistake.', url: '/games/simon-says/', emoji: '🟢', gradient: 'linear-gradient(135deg, #22c55e, #8b5cf6)', tags: ['skill', 'classic', 'highscore'], difficulty: 3, featured: false, status: 'live', publishedAt: '2026-08-20', popularity: 66 },
  { id: 'color-match', title: 'Color Match', description: 'Choose the correct color word before the timer runs out.', url: '/games/color-match/', emoji: '🎨', gradient: 'linear-gradient(135deg, #f43f5e, #8b5cf6)', tags: ['skill', 'action', 'highscore'], difficulty: 2, featured: false, status: 'live', publishedAt: '2026-08-20', popularity: 63 },
];

module.exports = games;
